### PR TITLE
Fix send to specific/all users

### PR DESCRIPTION
**Pull request by ploebb**
**fix send to specific User with "@user message":**
regexp `\b` matches only between words.
-> Fixed to match at start of message and **only** the one word behind @ (non greedy). 

**fix send to all users #1 :**
commented the `break;` in the for-loop. I don't see why it should break there.

**fix rememberUsers #2 :**
see [comment below](https://github.com/ioBroker/ioBroker.telegram/pull/3#issuecomment-209498862)

### CODE REVIEW

**Comment by ploebb** [comment]
Just added a commit to make the username-matching case insensitive

**Comment by ploebb** [comment]
I just added another commit which fixes #2 
I just copied the code-snipped from the admin-config-html-file.

But for this fix to work, the file `admin/index.html` have to be copied to `/op/iobroker/iobroker-data/files/telegram.admin/index.html` overwriting the existing file. Just removing and adding the adapter in the webinterface did not work.

**Comment by GermanBluefox** [comment]
I forgot to remove break after I debugged it. Thank you

**Comment by ploebb** [comment]
> I forgot to remove break after I debugged it.

I guessed it's something like this

> Thank you

And I have to thank you for this amazing software you created! I really enjoy iobroker and its many adapters!

**Pull request merged**
