### PR TITLE
Add new objects: botSendMessageId, botSendChatId

### PR DESCRIPTION
**Pull request by Haba1234**

### CODE REVIEW

**Comment by Apollon77** [comment]
Please check the PR, tere are conflicts in the meantime. I want to accept it soon :-)

**Comment by Haba1234** [comment]
I do not understand what the problem is :(

**Comment by Apollon77** [comment]
See here in the PR page:

`This branch has conflicts that must be resolved
Use the web editor or the to resolve conflicts.
Conflicting files
main.js
`

**Comment by Haba1234** [comment]
looked, but still do not understand ...

**Comment by Apollon77** [comment]
There were changes to the master branch after you send in this pr. Because of this there is a merge conflict because your pr changes a code part that was changed in Master too. 

You need to pull from master and solve the merge conflict in your fork in the relevant branch you used for the pr. After this commit and the pr should get updated automatically

**Comment by Haba1234** [comment]
happened?

**Comment by Apollon77** [comment]
looks good. Will merge all of he PRs tomorrow

**Pull request merged**
