### PR TITLE
Added description of new functions and examples 

### PR DESCRIPTION
**Pull request by Haba1234**

### CODE REVIEW

**Comment by Apollon77** [comment]
Therer is effectively nothing to merge in here?!
if it's only to clean up your fork then please do that on your side :-)

**Comment by Haba1234** [comment]
Changes here https://github.com/ioBroker/ioBroker.telegram/pull/7/commits/423e1362780b8a44085cebe1f3180d842a754b1a.
Merge and Revert appeared because of incomprehensible problems with GitHub

**Comment by Apollon77** [comment]
But this is already merged ... you created here a new Pull-Request with no changes

**Comment by Haba1234** [comment]
Ok, I'll try to remake

**Pull request closed without merging**
