### PR TITLE
Update index_m.html

### PR DESCRIPTION
**Pull request by salambelgord**
scroll for Socks5

### CODE REVIEW

**Comment by BuZZy1337** [comment]
Could you please provide some Screenshots of that change?
I cannot see any problems with the scrolling of the config page now??

**Comment by GermanBluefox** [comment]
Fixed in other way: https://github.com/ioBroker/ioBroker.telegram/commit/929f72cd4f3ce16947fb7d3244fb31ef498d8348

**Comment by GermanBluefox** [comment]
Thank you for showing the problem :)

**Comment by salambelgord** [comment]
Эт вам благодарность...класный продукт...а когда представляю проделаную работу аж страшно

**Pull request closed without merging**
